HIVE-107. Case structure for bin/hive. (Edward Capriolo via zshao)
git-svn-id: https://svn.apache.org/repos/asf/hadoop/hive/trunk@727617 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/bin/hive b/bin/hive
--- a/bin/hive
+++ b/bin/hive
@@ -100,29 +100,55 @@ if [ ! -f ${HADOOP} ]; then
   exit 4;
 fi
 
-if [ "$1" == "service" ]; then
-  shift
-  CLASS=org.apache.hadoop.hive.service.HiveServer
-  JAR=${HIVE_LIB}/hive_service.jar
-  if [ "$HIVE_PORT" != "" ]; then
-    HIVE_OPTS=$HIVE_PORT
-  fi
-else
-  CLASS=org.apache.hadoop.hive.cli.CliDriver
-  JAR=${HIVE_LIB}/hive_cli.jar
-  # override default value of hadoop.bin.path to point to what we are running off
-  # if the user specified a -D override - this will be further overriden
-  export HIVE_OPTS="-hiveconf hadoop.bin.path=$HADOOP"
-fi
-
-
 if [ "${AUX_PARAM}" != "" ]; then
   HIVE_OPTS="$HIVE_OPTS -hiveconf hive.aux.jars.path=${AUX_PARAM}"
   AUX_JARS_CMD_LINE="-libjars ${AUX_PARAM}"
 fi
-#echo "CLASSPATH="$CLASSPATH
-#echo "AUX_LIB_PATH"=$AUX_PARAM
-#echo "HADOOP_OPTS="$HADOOP_OPTS
-# note: $@ only works in "$@"
-#echo $HADOOP jar $AUX_JARS_CMD_LINE $JAR $CLASS $HIVE_OPTS "$@"
-exec $HADOOP jar $AUX_JARS_CMD_LINE $JAR $CLASS $HIVE_OPTS "$@"
+
+SERVICE_LIST=""
+
+for i in "$bin"/ext/*.sh ; do
+  . $i
+done
+
+SERVICE=""
+HELP=""
+while [ $# -gt 0 ]; do
+  case "$1" in
+    --service)
+      shift
+      SERVICE=$1
+      shift
+      ;;
+    --help)
+      HELP=_help
+      shift
+      ;;
+    *)
+      break
+      ;;
+  esac
+done
+
+if [ "$SERVICE" = "" ] ; then
+  if [ "$HELP" = "_help" ] ; then
+    SERVICE="help"
+  else
+    SERVICE="cli"
+  fi
+fi
+
+TORUN=""
+for j in $SERVICE_LIST ; do
+  if [ "$j" = "$SERVICE" ] ; then
+    TORUN=${j}$HELP
+  fi
+done
+
+if [ "$TORUN" = "" ] ; then
+  echo "Service $SERVICE not found"
+  echo "Available Services: $SERVICE_LIST"
+  exit 5
+else
+  $TORUN "$@"
+fi
