initial merge of 0.8.1

diff --git a/bin/hive b/bin/hive
--- a/bin/hive
+++ b/bin/hive
@@ -42,6 +42,10 @@ while [ $# -gt 0 ]; do
       HELP=_help
       shift
       ;;
+    --debug*)
+      DEBUG=$1
+      shift
+      ;;
     *)
       break
       ;;
@@ -67,6 +71,11 @@ HIVE_LIB=${HIVE_HOME}/lib
 # needed for execution
 if [ ! -f ${HIVE_LIB}/hive-exec-*.jar ]; then
   echo "Missing Hive Execution Jar: ${HIVE_LIB}/hive-exec-*.jar"
+  exit 1;
+fi
+
+if [ ! -f ${HIVE_LIB}/hive-builtins-*.jar ]; then
+  echo "Missing Hive Builtins Jar: ${HIVE_LIB}/hive-builtins-*.jar"
   exit 1;
 fi
 
@@ -159,13 +168,15 @@ if [ ! -f ${HADOOP} ]; then
 fi
 
 # Make sure we're using a compatible version of Hadoop
-hadoop_version=$($HADOOP version | awk '{if (NR == 1) {print $2;}}');
+if [ "x$HADOOP_VERSION" == "x" ]; then
+    HADOOP_VERSION=$($HADOOP version | awk '{if (NR == 1) {print $2;}}');
+fi
 
 # Save the regex to a var to workaround quoting incompatabilities
 # between Bash 3.1 and 3.2
 hadoop_version_re="^([[:digit:]]+)\.([[:digit:]]+)(\.([[:digit:]]+))?.*$"
 
-if [[ "$hadoop_version" =~ $hadoop_version_re ]]; then
+if [[ "$HADOOP_VERSION" =~ $hadoop_version_re ]]; then
     hadoop_major_ver=${BASH_REMATCH[1]}
     hadoop_minor_ver=${BASH_REMATCH[2]}
     hadoop_patch_ver=${BASH_REMATCH[4]}
@@ -197,6 +208,16 @@ done
 for i in "$bin"/ext/util/*.sh ; do
   . $i
 done
+
+if [ "$DEBUG" ]; then
+  if [ "$HELP" ]; then
+    debug_help
+    exit 0
+  else
+    get_debug_params "$DEBUG"
+    export HADOOP_CLIENT_OPTS="$HADOOP_CLIENT_OPTS $HIVE_MAIN_CLIENT_DEBUG_OPTS"
+  fi
+fi
 
 TORUN=""
 for j in $SERVICE_LIST ; do
